### ISSUE TITLE
Unable to use Jackson deserializer

### ISSUE THREAD

**Issue by pawelsalawa** [alapierre/ksef-java-rest-client#113]
Jackson mapper is unable to deserialize `io.alapierre.ksef.client.model.rest.auth.InitSignedResponse` (or any model class whatsoever), because they are annotated with Lombok's `@Builder` but there is no `@Jacksonized` annotation on them. The result is:
```
Cannot construct instance of `io.alapierre.ksef.client.model.rest.auth.InitSignedResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```
when trying to deserialize correct response from the KSeF.

**Comment by pawelsalawa** [comment]
I've added relevant changes to PR #112. I have not used `@Jacksonized` after all, because it depends on `jackson-databind` dependency, which is not wanted in the `ksef-api` module. I've used constructor-related annotations.

**Comment by alapierre** [comment]
thank you for that i will look in PR and merge it soon

**Comment by pawelsalawa** [comment]
I've closed the PR, as I had to do even more changes to make it (kind of) work. Finally I could not make a proper authentication with token, despite verifying the whole flow dozens of times. I don't know what was wrong. I've implemented everything from scratch by myself and it works. I'm not able to tell what was wrong here, unfortunately.

**Comment by alapierre** [comment]
sometime it is only 21304 `NoAuthenticationException` which is only a transient error and requires waiting a few seconds before attempting again. If you can obtain token, and first operation made with new one fails, probably it is 21304

**Comment by alapierre** [comment]
ok, I cherry picket two of your changes into master branch (model changes and `batchTypes.xsd`).

**Comment by alapierre** [comment]
let me know if you need any help

**Comment by alapierre** [comment]
ok, so I will close this issue
