### ISSUE TITLE
no main manifest attribute, in ksef-sample-2.0.8-SNAPSHOT.jar

### ISSUE THREAD

**Issue by p-mironiuk** [alapierre/ksef-java-rest-client#27]
Witam Serdecznie Zacnego i Utalentowanego Kolegę,

W trakcie swoich prób poznania platformy KSeF próbuję uruchomić Pana projekt, żeby zbadać tę "bestię".
Co mi się udało: 
1)sklonować na dysk na moim komputerku z Ubuntu 20.04, 
2)zrobić mvn install

Powstał ~/.m2/repository/..../ksef-sample-2.0.8-SNAPSHOT.jar , świetnie.

Próbuję go odpalić z wiersza poleceń **java -jar ksef-sample-2.0.8-SNAPSHOT.jar**
Wynik>  **no main manifest attribute, in ksef-sample-2.0.8-SNAPSHOT.jar**

Czy coś pominąłem, czy tak naprawdę za dużo się spodziewam po tym ksef-sample.. 
a chciałbym się tym pobawić , podstawić inny NIP, zobaczyć jaki podpis wyjdzie itp.itd.

Od razu się przyznaję,  że nie jestem mocny z Javy, zaś swoje próby będę popełniał w C# i w Go.

Z góry dziękuję za odpowiedź i Pozdrawiam :-) !

**Comment by alapierre** [comment]
cześć,

to jest biblioteka, która ma ułatwić integrację a nie gotowa aplikacja,
która ma interfejs użytkownika. Dodajesz ją jako zależność - nie musisz
kompilować samodzielnie, bo zarówno stabilna wersja skompilowana  jak i
snapshot jest dostępna w głównym repo mavena. Mając zależnośc, możesz
używać klienta i komunikować się z KSeF - najpierw trzeba
się uwierzytelnić, za pomocą podpisu elektronicznego.

Jeśli chodzi o Go, to chętnie pomogę - chciałem napisać podobnego do tego w
Javie klienta w Go, ale na razie nie było czasu.

wt., 21 cze 2022 o 12:28 p-mironiuk ***@***.***> napisał(a):

**Comment by p-mironiuk** [comment]
Dzięki za szybką odpowiedź!

Spróbuję w takim razie zrobić jakiegoś prostego klienta używając Twojej biblioteki.
Tak naprawdę , na ten moment potrzebuję przykładu podpisanego InitRequest, po to żebym nauczył się podobny przygotowywać z użyciem Microsoft.Xades - bo to znam.
Ok, będę próbował! :-)

Jeśli chodzi o Go, to pół roku temu wygenerowałem kod z yaml, do specyfikacji 0.0.2 jaka była w tamtej chwili. 
Siadam do tego teraz, jest wersja 1.0.3 specyfikacji i z tamtego nic nie działa. 
Wszystko się zmieniło !
Polska państwowa informatyka , ech .... :-/

Jeśli uda mi się coś wartościowego uzyskać w tym Go, to dam Ci znać !

Dziękuję
Pozdrawiam
Przemek
