### ISSUE TITLE
Pliki xsd authRequest maja zahardcodowane url ze środowiska testowego

### ISSUE THREAD

**Issue by robertkasperczyk** [alapierre/ksef-java-rest-client#87]
Zauważyłem, że tu:
https://github.com/alapierre/ksef-java-rest-client/blob/master/ksef-xml-model/src/main/xsd/authRequest.xsd#L12
Importy są zahardcodowane na ksef-test. Myślę, zę może to być problem z dwóch powodów:
* ksef-test częściej będzie wyłączany i wtedy nie możliwe będzie korzystanie np ze środowiska produkcyjnego
* mogą wystąpić pewne różnice między środowiskami gdy jakieś zmiany zostaną np najpierw wprowdzaone na ksef-test

Myślę, że można też rozważyć dodanie tych plików xsd per env i wybieranie na podstawie przesłanego env (analogicznie do wyboru klucza publicznego).

**Comment by robertkasperczyk** [comment]
Nie wiem czy nie najprostszym rozwiązaniem na ten moment będzie po prostu używanie zawsze linku do produkcyjnego KSeFu, to pozwoli uniknąć problemu z dostępnością.

Odnośnie obsługi środowisk, to można by się zastanowić nad usprawnieniami. 
Na przykład sam zderzyłem się z problemem, podwójnej definicji środowiska w przypadku  `KsefTokenFacade` musimy podać env jako parametr dla `OkHttpApiClient` oraz jako argument dla wywołania `authByToken`.
Może lepiej byłoby podwać go tylko raz - dla tworzenia obiektu API a następnie pobierać z niego w metodzie `authByToken`?
Ale to w sumie osobny temat i bardziej ewentualny improvement. 

Mógłbyś rozwinąć czemu plik per env nie zabezpieczy przed drugim problemem? I ewentualnie jakie widzisz wady takiego rozwiązania? 

Jeśli doszlibyśmy do porozumienia to w razie czego zgłaszam się na ochotnika do poprawienia tego. :)

**Comment by alapierre** [comment]
hej, 

podstawowy problem polega na tym, że model jest generowany podczas budowania na podstawie schemy. Jeśli różne środowiska będą miały różne schemy, to pojawi się problem - musielibyśmy mieć różne build'y na różne środowiska. To prawda, że przy logowaniu, pobierana jest schema ze strony MF, ponieważ XML żądania autoryzacyjnego jest obecnie walidowany. Zainspirowany Twoim komentarzem dodałem możliwość włączania i wyłączania walidacji. Ustawienie property systemowego `io.alapierre.ksef.validateAuthRequestXML` na false, spowoduje że walidacja nie będzie wykonywana i schema nie będzie pobierana. Cy to dobre rozwiązanie, żeby nie walidować XML - pewnie nie. Lepiej by było, tak jak mówisz, trzymać trzy wersje schematu i wybierać odpowiednią, na podstawie wartości `env`. To rozwiąże częściowo problem i myślę, że warto to zaimplementować. Przy czym, dla zgodności wstecznej, lepiej było by domyślnie zostawić schemę z testu. 

Można także spróbować pobrać te dodatkowe pliki schematów:
- https://ksef-test.mf.gov.pl/schema/gtw/svc/types/2021/10/01/0001/gtwTypes.xsd
- https://ksef-test.mf.gov.pl/schema/gtw/svc/online/types/2021/10/01/0001/onlineTypes.xsd

i umieścić je w aplikacji. Prawdziwy problem to fakt, że MF trzyma te schematy na środowisku a nie w jednym miejscu, wspólnym dla wszystkich środowisk. Rozwiązanie z pobraniem schamatów ma także dodatkową zaletę - aplikacja nie będzie musiała po nie sięgać przy każdym logowaniu się. Nie jestem pewien, ale raczej pobrane schemy są zapisywane w cache przez JDK (mogę się mylić - trzeba by to sprawdzić np. WireShark'iem). To nadal nie rozwiązuje podstawowego problemu - generowania modelu ze schematu, w przypadku gdy schemy będą różne.

Jeśli chodzi o pozbycie się podwójnego wskazywania środowiska - trzeba je podawać dwa razy, to bo są obecnie dwie niezelżenie klasy - a nawet osobne moduły. Może być trudno, zrobić to sensownie. Zdecydowałem się na osobne moduły dla fasad, bo nie każdy potrzebuje obu na raz.

**Comment by alapierre** [comment]
wypchnąłem cześć zmian związanych z walidacją i budowaniem na podstawie lokalnej schemy XML. Zobacz i daj znać co myślisz. Nie robiłem jeszcze testów na odłączonym necie, żeby się upewnić, że na pewno nie będzie pobierał sachem.

**Comment by robertkasperczyk** [comment]
Tak, po tych poprawkach na pewno wygląda to lepiej, szczególnie w kwestii dostępności, bo najbardziej obawiałem się tego, że niedostępność ksef-test spowoduje niedziałanie biblioteki w środowisku produkcyjnym. Dzięki za ogarnięcie sprawy.

**Comment by madmak2005** [comment]
Część i dzięki za Twoją pracę. Mam pytanie, czemu takie przykładowe uruchomienie nie działa poprawnie. Wysyłam fakturę i widzę ją w systemie KSeF ale nie mogę pobrać numeru faktury z systemu KSeF. Chciałem od razu po wysyłce przypisać fakturze we własnym systemie numer z systemu KSeF. 

Uruchamiam:
 invoiceApi.invoiceStatus(response.getElementReferenceNumber(), sessionToken);
lub (bo nie jestem pewny, który numer należy użyć)
 invoiceApi.invoiceStatus(response.getReferenceNumber(), sessionToken);

ale zawsze dostaję na to 
`{"exception":{"serviceCtx":"default","serviceCode":"D4C918CD-0079-4CFF-836C-C4ADB666A9B2","serviceName":"exception.handler","timestamp":"2023-11-22T08:53:53.788Z","exceptionDetailList":[{"exceptionCode":21180,"exceptionDescription":"Nieprawidłowe żądanie."}]}} `

Fragment kodu:
`private SentInvoiceStatus wyslijFakture(Faktura faktura) {
		try {
			JsonSerializer serializer = new GsonJsonSerializer();
			ApiClient client = new OkHttpApiClient(serializer);
			InterfejsyInteraktywneSesjaApi sesjaApi = new InterfejsyInteraktywneSesjaApi(client);
			KsefTokenFacade facade = new KsefTokenFacade(sesjaApi);
	        InitSignedResponse session = facade.authByToken(Environment.TEST, NIP_FIRMY, IdentifierType.onip, token);
	        String sessionToken = session.getSessionToken().getToken();
			InterfejsyInteraktywneFakturaApi invoiceApi = new InterfejsyInteraktywneFakturaApi(client);
			@NotNull SendInvoiceResponse response = invoiceApi.invoiceSend(faktura.toString().getBytes("UTF-8"), sessionToken);
			
			InvoiceStatusResponse status = invoiceApi.invoiceStatus(response.getElementReferenceNumber(), sessionToken);
			/*
			 * status dla getReferenceNumber() też zwraca błąd
			 * InvoiceStatusResponse status = invoiceApi.invoiceStatus(response.getReferenceNumber(), sessionToken);
			 */
			sesjaApi.terminateSession(sessionToken);
			return new SentInvoiceStatus(response, status);
		} catch (ApiException ex) {
			System.out.printf("Błąd wywołania API %d (%s) opis błędu %s", ex.getCode(), ex.getMessage(),
					ex.getResponseBody());
		} catch (IOException e) {
			System.out.println(e.getMessage());
		} catch (ParseException e) {
			e.printStackTrace();
		}
		return null;
	}`
